### ISSUE TITLE
error when training the GNMT

### ISSUE THREAD

**Issue by ZixuanLiang** [tensorflow/nmt#108]
Hello, I want to train the GNMT for English-Chinese translation. I follow the example command for training the GNMT WMT German-English model, but there is an error:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ec2-user/neural_machine_translation/nmt/nmt.py", line 28, in <module>
    from . import inference
  File "nmt/inference.py", line 25, in <module>
    from . import attention_model
  File "nmt/attention_model.py", line 22, in <module>
    from . import model
  File "nmt/model.py", line 27, in <module>
    from . import model_helper
  File "nmt/model_helper.py", line 9, in <module>
    from tensorflow.python.ops import lookup_ops
ImportError: cannot import name lookup_ops

I am running Tensorflow 1.1.0 with GPU support on Linux.

**Comment by chaoyu0804** [comment]
I guess the NMT model needs Tensorflow 1.2+

**Comment by Vab-jain** [comment]
I have tensorflow 1.6 installed. Still, I get a similar error. Here is a screenshot.
Can you help me out?

![tensor](https://user-images.githubusercontent.com/22465402/37253441-c7adbe60-2557-11e8-9386-82741a7db286.png)

**Comment by Artificial2idiot** [comment]
I have  the same problem, hope someone help us , maybe it is related to tensorflow version?

**Comment by oahziur** [comment]
@Vab-jain Does remove the import and replace `lookup_ops.index_to_string_table_from_file` with `tf.contrib.lookup.index_to_string_table_from_file` works for you in tf 1.6?

**Comment by arunvarma99910** [comment]
which lines should be replace
