### ISSUE TITLE
when i used vi-en works well ,but en-zh is wrong,How to solve it?

### ISSUE THREAD

**Issue by zero1207** [tensorflow/nmt#116]
2017-09-19 10:28:50.708723: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 10:28:50.708787: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 10:28:50.708808: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 10:28:51.222401: W tensorflow/core/framework/op_kernel.cc:1158] Failed precondition: HashTable has different value for same key. Key 被 has 4 and trying to add value 20
2017-09-19 10:28:51.222404: W tensorflow/core/framework/op_kernel.cc:1158] Failed precondition: HashTable has different value for same key. Key the has 9 and trying to add value 25
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nmt/nmt/nmt/nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/nmt/nmt/nmt/nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/nmt/nmt/nmt/nmt.py", line 481, in run_main
    train_fn(hparams, target_session=target_session)
  File "nmt/train.py", line 318, in train
    train_model.model, model_dir, train_sess, "train")
  File "nmt/model_helper.py", line 251, in create_or_load_model
    session.run(tf.tables_initializer())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: <exception str() failed>

**Comment by chaoyu0804** [comment]
"""
HashTable has different value for same key. Key 被 has 4 and trying to add value 20
"""
I guess the word '被' exits in your vocabulary file more than once.

**Comment by tasx0823** [comment]
I meet the same problem,and don't know how to solve it.

**Comment by janenie** [comment]
I ran into the same problem, my source and target are both english (I am not doing the nmt experiment), could it be a potential bug? I have checked that the source and target vocab are unique

**Comment by oahziur** [comment]
@tasx0823 @janenie check if your vocab file has duplicated tokens.

**Comment by rockingdingo** [comment]
I run into the same problem.... And I am using the unique vocabulary. FailedPreconditionError (see above for traceback): HashTable has different value for same key. Key <unk> has 0 and trying to add value 28626

**Comment by tasx0823** [comment]
@rockingdingo check the vocabulary if there exists two same word. if you use the official tensorflow tutorial for nmt,check the path of the vocab.It may be a defraud.
