### ISSUE TITLE
How to allow the Encoder and Decoder have diffenrent number of layers?

### ISSUE THREAD

**Issue by FrisaSZ** [tensorflow/nmt#132]
Hi. I want to use encoder and decoder that have different number of layers. For now, they have same number of layer and same number of hidden unit. When using bidirectional encoder, num_bi_layers = int(num_layers / 2), the last states of encoder can still be used to initialize decoder. But if I change to num_bi_layers = num_layers. It does'nt work. Any suggestions about how to apply the last states of encoder to decoder when they have different number of layers and different number of hidden units?

This is the terminal output

```
frisasz@cooller:/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz$ source activate py3
(py3) frisasz@cooller:/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz$ python -m nmt.nmt \
     --attention=scaled_luong \
     --src=vi --tgt=en \
     --vocab_prefix=./nmt_data/vocab \
     --train_prefix=./nmt_data/train \
     --dev_prefix=./nmt_data/tst2012 \
     --test_prefix=./nmt_data/tst2013 \
     --out_dir=./nmt_attention_model \
     --num_train_steps=1000 \
     --steps_per_stats=100 \
     --encoder_type=bi \
     --num_layers=2 \
     --num_units=64 \
     --dropout=0.2 \
     --metrics=bleu

# Job id 0
# Loading hparams from ./nmt_attention_model/hparams
  saving hparams to ./nmt_attention_model/hparams
  saving hparams to ./nmt_attention_model/best_bleu/hparams
  attention=scaled_luong
  attention_architecture=standard
  batch_size=128
  beam_width=0
  best_bleu=0.3036104765433896
  best_bleu_dir=./nmt_attention_model/best_bleu
  bpe_delimiter=None
  colocate_gradients_with_ops=True
  decay_factor=0.98
  decay_steps=10000
  dev_prefix=./nmt_data/tst2012
  dropout=0.2
  encoder_type=bi
  eos=</s>
  epoch_step=1000
  forget_bias=1.0
  infer_batch_size=32
  init_op=uniform
  init_weight=0.1
  learning_rate=1.0
  length_penalty_weight=0.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=['bleu']
  num_buckets=5
  num_embeddings_partitions=0
  num_gpus=1
  num_layers=2
  num_residual_layers=0
  num_train_steps=1000
  num_units=64
  optimizer=sgd
  out_dir=./nmt_attention_model
  pass_hidden_state=True
  random_seed=None
  residual=False
  share_vocab=False
  sos=<s>
  source_reverse=False
  src=vi
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=./nmt_data/vocab.vi
  src_vocab_size=7709
  start_decay_step=0
  steps_per_external_eval=None
  steps_per_stats=100
  test_prefix=./nmt_data/tst2013
  tgt=en
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=./nmt_data/vocab.en
  tgt_vocab_size=17191
  time_major=True
  train_prefix=./nmt_data/train
  unit_type=lstm
  vocab_prefix=./nmt_data/vocab
# creating train graph ...
  num_bi_layers = 2, num_bi_residual_layers=0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
Traceback (most recent call last):
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/nmt.py", line 481, in run_main
    train_fn(hparams, target_session=target_session)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/train.py", line 283, in train
    single_cell_fn)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/train.py", line 94, in create_train_model
    single_cell_fn=single_cell_fn)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/attention_model.py", line 55, in __init__
    single_cell_fn=single_cell_fn)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/model.py", line 96, in __init__
    res = self.build_graph(hparams, scope=scope)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/model.py", line 234, in build_graph
    encoder_outputs, encoder_state, hparams)
  File "/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz/nmt/model.py", line 340, in _build_decoder
    scope=decoder_scope)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 286, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 244, in body
    nest.assert_same_structure(state, decoder_state)
  File "/home/frisasz/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 199, in assert_same_structure
    % (len_nest1, nest1, len_nest2, nest2))
ValueError: The two structures don't have the same number of elements.

First structure (11 elements): AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/Identity_3:0' shape=(?, 64) dtype=float32>, h=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/Identity_4:0' shape=(?, 64) dtype=float32>), 
LSTMStateTuple(c=<tf.Tensor 'dynamic_seq2seq/decoder/decoder/while/Identity_5:0' shape=(?, 64) 
dtype=float32>, h=<tf.Tensor 'dynamic_seq2seq/decoder/decoder/while/Identity_6:0' shape=(?, 64) 
dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'dynamic_seq2seq/decoder/decoder/while/Identity_7:0' 
shape=(?, 64) dtype=float32>, h=<tf.Tensor 'dynamic_seq2seq/decoder/decoder/while/Identity_8:0' 
shape=(?, 64) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/Identity_9:0' shape=(?, 64) dtype=float32>, h=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/Identity_10:0' shape=(?, 64) dtype=float32>)), attention=
<tf.Tensor 'dynamic_seq2seq/decoder/decoder/while/Identity_11:0' shape=(?, 64) dtype=float32>, time=
<tf.Tensor 'dynamic_seq2seq/decoder/decoder/while/Identity_12:0' shape=() dtype=int32>, alignments=
<tf.Tensor 'dynamic_seq2seq/decoder/decoder/while/Identity_13:0' shape=(?, ?) dtype=float32>, 
alignment_history=())

Second structure (7 elements): AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/attention/multi_rnn_cell/
cell_0/cell_0/basic_lstm_cell/add_1:0' shape=(?, 64) dtype=float32>, h=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/attention/multi_rnn_cell/
cell_0/cell_0/basic_lstm_cell/mul_2:0' shape=(?, 64) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/attention/multi_rnn_cell/
cell_1/cell_1/basic_lstm_cell/add_1:0' shape=(?, 64) dtype=float32>, h=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/attention/multi_rnn_cell/
cell_1/cell_1/basic_lstm_cell/mul_2:0' shape=(?, 64) dtype=float32>)), attention=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/concat_2:0' shape=(?, 
64) dtype=float32>, time=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/add:0' shape=() 
dtype=int32>, alignments=<tf.Tensor 
'dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/Softmax:0' shape=(?, ?) 
dtype=float32>, alignment_history=())
(py3) frisasz@cooller:/media/frisasz/DATA/FSZ_Work/dl2/nmt_fsz$ 
```

**Comment by Halfish** [comment]
I don't understand why should we set `num_bi_layers = int(num_layers / 2)`, isn't that weird to use forward and backward encoder state to initialize two following layers of decoder? 

check the origin codes [nmt/model.py#L536-L546](https://github.com/tensorflow/nmt/blob/master/nmt/model.py#L536-L546)

I simple concat the forward and backward state at the same layer, and map from the bidirectional encoder hidden size to decoder hidden size using a transition matrix.

**Comment by JustinLin610** [comment]
I also met similar problem in my code, and I feel confused about this error:

ValueError: The two structures don't have the same number of elements. First structure: AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'decode/decoder/while/Identity_3:0' shape=(?, 128) dtype=float32>, h=<tf.Tensor 'decode/decoder/while/Identity_4:0' shape=(?, 128) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'decode/decoder/while/Identity_5:0' shape=(?, 128) dtype=float32>, h=<tf.Tensor 'decode/decoder/while/Identity_6:0' shape=(?, 128) dtype=float32>)), attention=<tf.Tensor 'decode/decoder/while/Identity_7:0' shape=(64, 128) dtype=float32>, time=<tf.Tensor 'decode/decoder/while/Identity_8:0' shape=() dtype=int32>, alignments=<tf.Tensor 'decode/decoder/while/Identity_9:0' shape=(64, ?) dtype=float32>, alignment_history=()), second structure: AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'decode/decoder/while/BasicDecoderStep/decoder/attention_wrapper/attention_wrapper/multi_rnn_cell/cell_0/cell_0/lstm_cell/lstm_cell/add_1:0' shape=(64, 128) dtype=float32>, h=<tf.Tensor 'decode/decoder/while/BasicDecoderStep/decoder/attention_wrapper/attention_wrapper/multi_rnn_cell/cell_0/cell_0/lstm_cell/lstm_cell/mul_2:0' shape=(64, 128) dtype=float32>),), attention=<tf.Tensor 'decode/decoder/while/BasicDecoderStep/decoder/attention_wrapper/attention_layer/MatMul:0' shape=(64, 128) dtype=float32>, time=<tf.Tensor 'decode/decoder/while/BasicDecoderStep/decoder/attention_wrapper/add:0' shape=() dtype=int32>, alignments=<tf.Tensor 'decode/decoder/while/BasicDecoderStep/decoder/attention_wrapper/Softmax:0' shape=(64, ?) dtype=float32>, alignment_history=()).

**Comment by FrisaSZ** [comment]
@Halfish Thanks for your advice. 

For now, I use a slightly different method. Only the last encoder layer 's final states are used and they are pass to FC layers (the number of FC layers is equal to the number of decoder layers). Then the outputs of FC layers can be used to initialize the decoder layers. 
Since I've made a large amount of modification to this project for an ocr task, it's not appropriate to submit a pull request. This is my code of the transition.
```
                num_decoder_layers = hparams.num_decoder_layers
                num_decoder_units = hparams.num_decoder_units
                if num_encoder_layers == 1:
                    top_forward_state = bi_encoder_state[0]
                    top_backward_state = bi_encoder_state[1]
                else:
                    top_forward_state = bi_encoder_state[0][-1]
                    top_backward_state = bi_encoder_state[1][-1]

                c_forward = top_forward_state.c
                h_forward = top_forward_state.h
                c_backward = top_backward_state.c
                h_backward = top_backward_state.h
                c_last = tf.concat((c_forward, c_backward), -1)
                h_last = tf.concat((h_forward, h_backward), -1)
                encoder_state = []
                for idx in range(num_decoder_layers):
                    c_decoder = tf.layers.dense(
                        inputs=c_last,
                        units=num_decoder_units,
                        use_bias=True,
                        activation=None,
                        kernel_initializer=tf.truncated_normal_initializer(),
                        name='encoder_c_state_projection_layer_' + str(idx))
                    h_decoder = tf.layers.dense(
                        inputs=h_last,
                        units=num_decoder_units,
                        use_bias=True,
                        activation=None,
                        kernel_initializer=tf.truncated_normal_initializer(),
                        name='encoder_h_state_projection_layer_' + str(idx))
                    decoder_state = tf.contrib.rnn.LSTMStateTuple(c=c_decoder, h=h_decoder)
                    encoder_state.append(decoder_state)
                encoder_state = tuple(encoder_state) if len(encoder_state) > 1 else encoder_state[0]
```
