### ISSUE TITLE
Failed to run the inference test step for Vi-en but training completed without error.

### ISSUE THREAD

**Issue by bharathichezhiyan** [tensorflow/nmt#135]
python -m nmt.nmt --cpus=2 --src=vi --tgt=en --out_dir=nmt_model/ --inference_input_file=nmt_data/tst2013.vi --inference_output_file=nmt_model/output_infer.en
# Job id 0
# Loading hparams from nmt_model/hparams
  saving hparams to nmt_model/hparams
  saving hparams to nmt_model/best_bleu/hparams
  attention=
  attention_architecture=standard
  batch_size=128
  beam_width=0
  best_bleu=5.809653463551168
  best_bleu_dir=nmt_model/best_bleu
  bpe_delimiter=None
  check_special_token=True
  colocate_gradients_with_ops=True
  decay_factor=0.98
  decay_steps=10000
  dev_prefix=None
  dropout=0.2
  encoder_type=uni
  eos=</s>
  epoch_step=0
  forget_bias=1.0
  infer_batch_size=32
  init_op=uniform
  init_weight=0.1
  learning_rate=1.0
  learning_rate_warmup_factor=1.0
  learning_rate_warmup_steps=0
  length_penalty_weight=0.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=['bleu']
  num_buckets=5
  num_embeddings_partitions=0
  num_gpus=1
  num_layers=2
  num_residual_layers=0
  num_train_steps=12000
  num_translations_per_input=1
  num_units=32
  optimizer=sgd
  out_dir=nmt_model/
  override_loaded_hparams=True
  pass_hidden_state=True
  random_seed=None
  residual=False
  share_vocab=False
  sos=<s>
  source_reverse=False
  src=vi
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=nmt_data/vocab.vi
  src_vocab_size=7709
  start_decay_step=0
  steps_per_external_eval=None
  steps_per_stats=100
  test_prefix=None
  tgt=en
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=nmt_data/vocab.en
  tgt_vocab_size=17191
  time_major=True
  train_prefix=None
  unit_type=lstm
  vocab_prefix=None
# creating infer graph ...
  num_layers = 2, num_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  start_decay_step=0, learning_rate=1, decay_steps 10000, decay_factor 0.98, learning_rate_warmup_steps=0, learning_rate_warmup_factor=1, starting_learning_rate=1
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (7709, 32), 
  embeddings/decoder/embedding_decoder:0, (17191, 32), 
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (64, 128), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (128,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (64, 128), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (128,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (64, 128), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (128,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (64, 128), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (128,), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (32, 17191), 
2017-09-29 16:36:42.991156: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
Traceback (most recent call last):
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/bharaj/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 467, in raise_exception_on_not_ok_status
    c_api.TF_GetCode(status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128] rhs shape= [512]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias, save/RestoreV2_3)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bharaj/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bharaj/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bharaj/nmt/nmt/nmt.py", line 518, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/bharaj/nmt/nmt/nmt.py", line 511, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/bharaj/nmt/nmt/nmt.py", line 490, in run_main
    trans_file, hparams, num_workers, jobid)
  File "/home/bharaj/nmt/nmt/inference.py", line 110, in inference
    hparams)
  File "/home/bharaj/nmt/nmt/inference.py", line 136, in single_worker_inference
    infer_model.model, ckpt, sess, "infer")
  File "/home/bharaj/nmt/nmt/model_helper.py", line 407, in load_model
    model.saver.restore(session, ckpt)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1662, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128] rhs shape= [512]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias, save/RestoreV2_3)]]

Caused by op 'save/Assign_3', defined at:
  File "/home/bharaj/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bharaj/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bharaj/nmt/nmt/nmt.py", line 518, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/bharaj/nmt/nmt/nmt.py", line 511, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/bharaj/nmt/nmt/nmt.py", line 490, in run_main
    trans_file, hparams, num_workers, jobid)
  File "/home/bharaj/nmt/nmt/inference.py", line 102, in inference
    infer_model = model_helper.create_infer_model(model_creator, hparams, scope)
  File "/home/bharaj/nmt/nmt/model_helper.py", line 205, in create_infer_model
    extra_args=extra_args)
  File "/home/bharaj/nmt/nmt/model.py", line 186, in __init__
    self.saver = tf.train.Saver(tf.global_variables())
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1214, in __init__
    self.build()
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1223, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1259, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 747, in _build_internal
    restore_sequentially, reshape)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 435, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3090, in create_op
    op_def=op_def)
  File "/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1638, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [128] rhs shape= [512]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias, save/RestoreV2_3)]]

**Comment by oahziur** [comment]
@bharathichezhiyan 

I think the `override_loaded_hparams` should set to False when doing inference so we don't accidentally update the model configuration to default.

I just update the master branch, so it should be turn off by default. Using the training and inference instructions with a fresh output dir should work now.

**Comment by bharathichezhiyan** [comment]
I tried to give flags --override_loaded_hparams=False in inference hoping to not to train the model. It didnot work. Downloaded the master branch again and Training again. It takes all the processes in the server.

**Comment by oahziur** [comment]
@bharathichezhiyan 

What is the error you see this time? Can you share it here? Especially the error log of the one synced with the master.

If you just give `--override_loaded_hparams=False` to a previous failed model, it won't work because the `hparams` on the disk has been updated by the previous failed runs to incorrect value with the checkpoints.

**Comment by bharathichezhiyan** [comment]
Thanks @oahziur oahziur
I rerun the model it is working now. 
 I still could not figure out how to control the maximum number of processes. Do I have to change it the code? I could not find any flags in nmt.py relating to the maximum number of process. Even with the number of GPU flags, it does not seem to be working.

**Comment by oahziur** [comment]
Hi @bharathichezhiyan , I have answered the GPU and processes related question in #136.
