### ISSUE TITLE
How to run the tests ?

### ISSUE THREAD

**Issue by flavianh** [tensorflow/nmt#15]
I tried 2 ways:

* `python model_test.py`
* `python nmt/model_test.py`

with both python27 and python36

In both cases, I get the error

```
Traceback (most recent call last):
  File "model_test.py", line 26, in <module>
    from . import attention_model
ImportError: cannot import name 'attention_model'
```

I also tried to add the nmt directory to PYTHONPATH, without success.

It interests me very much that you've written tests, but I find no way to run them. Any help would be appreciated :)

**Comment by flavianh** [comment]
Got it: `python -m nmt.model_test`

**Comment by oahziur** [comment]
Hi @flavianh, Can you attach the error log?

**Comment by fansiawang** [comment]
You can execute the following command to test your model:
```
python -m nmt.nmt \
     		--src=vi --tgt=en \
     		--vocab_prefix=./nmt/nmt_data/vocab  \
     		--out_dir=./nmt//nmt_attention_model \
     		--model_dir=./nmt//nmt_model \
     		--inference_input_file=./nmt//my_infer_file.vi \
    		--inference_output_file=./nmt//nmt_attention_model/output_infer
```
I use this command to test my model successfully. This command can also be found in the NMT tutorial, but it will be some different.  Maybe you can try both of them. Hope that can help you!

**Comment by cyzLoveDream** [comment]
hello! i have a problem when i run test:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\transtate\nmt\nmt\nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:\transtate\nmt\nmt\nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "E:\transtate\nmt\nmt\nmt.py", line 481, in run_main
    train_fn(hparams, target_session=target_session)
  File "E:\transtate\nmt\nmt\train.py", line 329, in train
    sample_tgt_data)
  File "E:\transtate\nmt\nmt\train.py", line 248, in run_full_eval
    sample_src_data, sample_tgt_data)
  File "E:\transtate\nmt\nmt\train.py", line 162, in run_sample_decode
    infer_model.batch_size_placeholder, summary_writer)
  File "E:\transtate\nmt\nmt\train.py", line 529, in _sample_decode
    utils.print_out("    src: %s" % src_data[decode_id])
  File "E:\transtate\nmt\nmt\utils\misc_utils.py", line 66, in print_out
    print(out_s, end="", file=sys.stdout)
UnicodeEncodeError: 'gbk' codec can't encode character '\u0111' in position 12: illegal multibyte sequence

**Comment by Lee-L-Boyd** [comment]
Seems to primarily be missing a module called portpicker when I run the test.

**Comment by oahziur** [comment]
@Lee-L-Boyd you can install it with `pip install portpicker`. It is a dependency of `tf.test.create_local_cluster()` used by `model_test.py`.

**Comment by Lee-L-Boyd** [comment]
@oahziur thanks!

**Comment by zhao900805** [comment]
same issue here, then I realized that I should not not use command "python XXX.py" to run the file, please use the command from tutorial instead.
