### ISSUE TITLE
Why  i run iterator_utils_test.py and it can't equals to the given samples?

### ISSUE THREAD

**Issue by MrKZZ** [tensorflow/nmt#154]
When i run this file,there 5 tests and 3 failed.  testGetIterator()  testGetIteratorWithshard()  testGetIteratorWithSkipCount()  can not just correctly fit the given samples ``` I wonder the reason.
And I also want to know can this model used for english and chinese translation ? thanks

**Comment by Lee-L-Boyd** [comment]
I had this same problem.  It worries me a little if the simple test cases are failing how well the model works.

**Comment by Lee-L-Boyd** [comment]
python iterator_utils_test.py
2018-01-04 16:22:31.134661: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-04 16:22:31.243367: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-04 16:22:31.243639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7465
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.39GiB
2018-01-04 16:22:31.243654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
.2018-01-04 16:22:31.412975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
I I I 0
not equal where =  (array([0, 0]), array([0, 1]))
not equal lhs =  [-1 -1]
not equal rhs =  [2 2]
F2018-01-04 16:22:31.470028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
.2018-01-04 16:22:31.529091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
not equal where =  (array([0, 0]), array([1, 2]))
not equal lhs =  [0 3]
not equal rhs =  [2 0]
F.
======================================================================
FAIL: testGetIterator (__main__.IteratorUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "iterator_utils_test.py", line 80, in testGetIterator
    source_v)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1037, in assertAllEqual
    np.testing.assert_array_equal(a, b)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 33.3333333333%)
 x: array([[-1, -1,  0],
       [ 2,  0,  3]])
 y: array([[2, 2, 0],
       [2, 0, 3]], dtype=int32)

======================================================================
FAIL: testGetIteratorWithSkipCount (__main__.IteratorUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "iterator_utils_test.py", line 246, in testGetIteratorWithSkipCount
    source_v)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 1037, in assertAllEqual
    np.testing.assert_array_equal(a, b)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 854, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 33.3333333333%)
 x: array([[ 2,  0,  3],
       [-1, -1,  0]])
 y: array([[ 2,  2,  0],
       [-1, -1,  0]], dtype=int32)

----------------------------------------------------------------------
Ran 5 tests in 0.550s

FAILED (failures=2)

**Comment by Lee-L-Boyd** [comment]
I think there might be an issue with the way I am running the test case.  I had to change the import to pull straight from the file, since I am not running the thing as a package.  So my import looks like:
_import iterator_utils_copy as iterator_utils_
Where iterator_utils_copy is just a copy of iterator_utils in the folder.  I doubt this would have any impact.  The problem seem to stem from the thing throwing away the first sentence.  When I change the second sentence to: "c b a", then I get this mismatch:

 x: array([[-1, -1,  0],
       [ 2,  0,  3]])
 y: array([[2, 1, 0],
       [2, 0, 3]], dtype=int32)
instead of 2,2,0 as before.  The strange thing is that this happens regardless of src_max_len.
