### ISSUE TITLE
UnicodeEncodeError when run branch tf.12 code.

### ISSUE THREAD

**Issue by luosmart** [tensorflow/nmt#169]
```
 File "~/nmt_tf/nmt/train.py", line 530, in _sample_decode
    utils.print_out("    ref: %s" % tgt_data[decode_id])
  File "~/nmt_tf/nmt/utils/misc_utils.py", line 66, in print_out
    print(out_s, end="", file=sys.stdout)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u1ebf' in position 17: ordinal not in range(256)
```

**Comment by sushant097** [comment]
When i enter in windows shell:
$ python -m nmt.py \
>     --src=vi --tgt=en \
>     --vocab_prefix=tmp/nmt_data/vocab  \
>     --train_prefix=tmp/nmt_data/tranin \
>     --dev_prefix=tmp/nmt_data/tst2012  \
>     --test_prefix=tmp/nmt_data/tst2013 \
>     --out_dir=tmp/nmt_model \
>     --num_train_step12000 \
>     --steps_per_stats=100 \
>     --num_layers=2 \
>     --num_units=128 \
>     --dropout=0.2 \
>     --metrics=bleu
When i run it, i get the following output:
# Job id 0
# Loading hparams from tmp/nmt_model\hparams
  saving hparams to tmp/nmt_model\hparams
  saving hparams to tmp/nmt_model\best_bleu\hparams
  attention=
  attention_architecture=standard
  batch_size=128
  beam_width=0
  best_bleu=0
  best_bleu_dir=tmp/nmt_model\best_bleu
  bpe_delimiter=None
  colocate_gradients_with_ops=True
  decay_factor=0.98
  decay_steps=10000
  dev_prefix=tmp/nmt_data/tst2012
  dropout=0.2
  encoder_type=uni
  eos=</s>
  epoch_step=0
  forget_bias=1.0
  infer_batch_size=32
  init_op=uniform
  init_weight=0.1
  learning_rate=1.0
  length_penalty_weight=0.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=['bleu']
  num_buckets=5
  num_embeddings_partitions=0
  num_gpus=1
  num_layers=2
  num_residual_layers=0
  num_train_steps=12000
  num_units=128
  optimizer=sgd
  out_dir=tmp/nmt_model
  pass_hidden_state=True
  random_seed=None
  residual=False
  share_vocab=False
  sos=<s>
  source_reverse=False
  src=vi
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=tmp/nmt_data/vocab.vi
  src_vocab_size=7709
  start_decay_step=0
  steps_per_external_eval=None
  steps_per_stats=100
  test_prefix=tmp/nmt_data/tst2013
  tgt=en
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=tmp/nmt_data/vocab.en
  tgt_vocab_size=17191
  time_major=True
  train_prefix=tmp/nmt_data/train
  unit_type=lstm
  vocab_prefix=tmp/nmt_data/vocab
WARNING:tensorflow:From E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\train.py:65: TextLineDataset.__init__ (from tensorflow.contrib.data.python.ops.readers) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.TextLineDataset`.
WARNING:tensorflow:From E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\utils\iterator_utils.py:106: Dataset.zip (from tensorflow.contrib.data.python.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.zip()`.
WARNING:tensorflow:From E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\utils\iterator_utils.py:118: calling Dataset.map (from tensorflow.contrib.data.python.ops.dataset_ops) with num_threads is deprecated and will be removed in a future version.
Instructions for updating:
Replace `num_threads=T` with `num_parallel_calls=T`. Replace `output_buffer_size=N` with `ds.prefetch(N)` on the returned dataset.
WARNING:tensorflow:From E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\utils\iterator_utils.py:118: calling Dataset.map (from tensorflow.contrib.data.python.ops.dataset_ops) with output_buffer_size is deprecated and will be removed in a future version.
Instructions for updating:
Replace `num_threads=T` with `num_parallel_calls=T`. Replace `output_buffer_size=N` with `ds.prefetch(N)` on the returned dataset.
WARNING:tensorflow:From E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\utils\iterator_utils.py:195: Dataset.group_by_window (from tensorflow.contrib.data.python.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `ds.apply(tf.contrib.data.group_by_window())`.
# creating train graph ...
  num_layers = 2, num_residual_layers=0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  start_decay_step=0, learning_rate=1, decay_steps 10000,decay_factor 0.98
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (7709, 128),
  embeddings/decoder/embedding_decoder:0, (17191, 128),
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (128, 17191), /device:GPU:0
# creating eval graph ...
  num_layers = 2, num_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  start_decay_step=0, learning_rate=1, decay_steps 10000,decay_factor 0.98
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (7709, 128),
  embeddings/decoder/embedding_decoder:0, (17191, 128),
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (128, 17191), /device:GPU:0
WARNING:tensorflow:From E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\inference.py:63: Dataset.from_tensor_slices (from tensorflow.contrib.data.python.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.from_tensor_slices()`.
# creating infer graph ...
  num_layers = 2, num_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  start_decay_step=0, learning_rate=1, decay_steps 10000,decay_factor 0.98
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (7709, 128),
  embeddings/decoder/embedding_decoder:0, (17191, 128),
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (128, 17191),
# log_file=tmp/nmt_model\log_1513055366
  created train model with fresh parameters, time 3.90s
  created infer model with fresh parameters, time 0.56s
  # 1340
Traceback (most recent call last):
  File "C:\Users\ProWinJVM\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ProWinJVM\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\ProWinJVM\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\nmt.py", line 481, in run_main
    train_fn(hparams, target_session=target_session)
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\train.py", line 329, in train
    sample_tgt_data)
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\train.py", line 248, in run_full_eval
    sample_src_data, sample_tgt_data)
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\train.py", line 162, in run_sample_decode
    infer_model.batch_size_placeholder, summary_writer)
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\train.py", line 529, in _sample_decode
    utils.print_out("    src: %s" % src_data[decode_id])
  File "E:\PY_New_Projects\My_practice CHATBOT\NMT_tf-1.2\nmt-tf-1.2\nmt\utils\misc_utils.py", line 66, in print_out
    print(out_s, end="", file=sys.stdout)
  File "C:\Users\ProWinJVM\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ead' in position 20: character maps to <undefined>
