### ISSUE TITLE
Attention Heatmap?

### ISSUE THREAD

**Issue by ngcabang** [tensorflow/nmt#227]
How do I create the attention heat map based from Attention model like the image below?

![phtqi](https://user-images.githubusercontent.com/30017963/34465294-1a412ca0-eee1-11e7-8a84-a5fa5bbcb6ca.png)

**Comment by oahziur** [comment]
Hi @ngcabang 

You can start with the code for generate the image summary [here](https://github.com/tensorflow/nmt/blob/365e7386e6659526f00fa4ad17eefb13d52e3706/nmt/attention_model.py#L174). That will generate a heat map without sentences on the left and top margin. The image will be displayed in the image section on Tensorboard.

**Comment by nave01314** [comment]
@oahziur I run into two issues with the template code for Attention summary generation:

When beam search is enabled, the above throws an [error](https://github.com/tensorflow/tensorflow/issues/13154). I'm assuming beam search and alignment history are not compatible right now.

When I disable beam search, I get the following error: 

```
Traceback (most recent call last):
  File "/home/nave01314/IdeaProjects/tf-nmt/main.py", line 19, in <module>
    infer_model = model_builder.create_infer_model(hparams)
  File "/home/nave01314/IdeaProjects/tf-nmt/model_builder.py", line 125, in create_infer_model
    tgt_vocab_table=tgt_vocab_table)
  File "/home/nave01314/IdeaProjects/tf-nmt/models.py", line 41, in __init__
    self.attn_summary = self.make_attention_summary(final_context_state)
  File "/home/nave01314/IdeaProjects/tf-nmt/models.py", line 192, in make_attention_summary
    attention_images = (final_context_state.alignment_history.stack())
AttributeError: 'tuple' object has no attribute 'stack'
```

**Comment by Hazepusik** [comment]
Hi, @ngcabang !
I faced the same problem now. Have you solved your issue?
Thanks

**Comment by ttrouill** [comment]
Same here, I would like to get each alignment map for each of the top-k translations when beam search is activated, is this planned any time soon? If not, what should be changed for this to work @oahziur ?

**Comment by oahziur** [comment]
@ttrouill @nave01314 Actually, I am not sure if the attention image for BeamSearch will be correct out of the box since we traversed the decoding tree in BeamSearchDecoder to get the final results, so I guess we will need to do the similar [gather_tree](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/gather_tree) operation in the end. We can revisit this after beam_search and alignment_history are compatible.

@nave01314 Can you print the `final_context_state.alignment_history` see what's inside the tuple?

**Comment by ttrouill** [comment]
@oahziur Ok thanks for the precisions, is there an already existing branch working on beam_search and alignment_history compatibility that I can follow/contribute?

**Comment by oahziur** [comment]
@ttrouill I don't know if there is any existing branch or pull request on this, but I think you can follow this [issue](https://github.com/tensorflow/tensorflow/issues/13154) to get update if there is any.

**Comment by ttrouill** [comment]
Looks like beam_search and alignment_history compatibility issue will soon be [resolved and merged]https://github.com/tensorflow/tensorflow/pull/13312#pullrequestreview-87614206)

**Comment by DaoD** [comment]
@nave01314 the same problem, how do you solve it?
I do not use beam search, but I still can't get the alignment.

**Comment by JulianZhang** [comment]
@oahziur Dear, I can see the attention image by tensorboard now , But there this is only one image for one step,  does that mean the image is for all training data?

How can I get  image for one given sentences?
