### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by WmBA** [tensorflow/nmt#240]
I am working through your nmt tutorials on a Windows 10 based laptop using Bash linux.
I've made it through the Vietnamese sections and am know working on the German example.
I hit a UnicodeDecodeError on the first record of the Vocab_Prefix file (see dump below).
My Bash terminal reports;
$ python Version.py
3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
Encoding = cp1252

My understanding of this is that the terminal uses cp1252 encoding (Windows 10 standard) but the NMT code is reading from files and specifies UTF8 encoding which I assume matches the script generated training data files.

Any suggestions would be most appreciated.

 !$ ./Train_DE_EN_2.py
 !# Job id 0
 !# Loading standard hparams from nmt/standard_hparams/wmt16_gnmt_4_layer.json
 !# hparams:
  src=de
  tgt=en
  train_prefix=c:/Users/wba/AppData/Local/Temp/wmt16/train.tok.clean.bpe.32000
  dev_prefix=c:/Users/wba/AppData/Local/Temp/wmt16/newstest2013.tok.bpe.32000
  test_prefix=c:/Users/wba/AppData/Local/Temp/wmt16/newstest2015.tok.bpe.32000
  out_dir=c:/SEI/Tools/Python/German/tmp/deen_gnmt
 !# Vocab file c:/Users/wba/AppData/Local/Temp/wmt16/vocab.bpe.32000.de exists
Traceback (most recent call last):
  File "C:\SEI\Tools\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\SEI\Tools\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\SEI\Tools\Python\German\nmt\nmt\nmt.py", line 605, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\SEI\Tools\Python\lib\site-packages\tensorflow\python\platform\app.py", line 129, in run
    _sys.exit(main(argv))
  File "C:\SEI\Tools\Python\German\nmt\nmt\nmt.py", line 598, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "C:\SEI\Tools\Python\German\nmt\nmt\nmt.py", line 562, in run_main
    out_dir, default_hparams, flags.hparams_path, save_hparams=(jobid == 0))
  File "C:\SEI\Tools\Python\German\nmt\nmt\nmt.py", line 527, in create_or_load_hparams
    hparams = extend_hparams(hparams)
  File "C:\SEI\Tools\Python\German\nmt\nmt\nmt.py", line 441, in extend_hparams
    unk=vocab_utils.UNK)
  File "C:\SEI\Tools\Python\German\nmt\nmt\utils\vocab_utils.py", line 52, in check_vocab
    vocab, vocab_size = load_vocab(vocab_file)
  File "C:\SEI\Tools\Python\German\nmt\nmt\utils\vocab_utils.py", line 41, in load_vocab
    for word in f:
  File "C:\SEI\Tools\Python\lib\codecs.py", line 642, in __next__
    line = self.readline()
  File "C:\SEI\Tools\Python\lib\codecs.py", line 555, in readline
    data = self.read(readsize, firstline=True)
  File "C:\SEI\Tools\Python\lib\codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: invalid continuation byte

**Comment by WmBA** [comment]
I switched to linux on a Macbook and worked around the problem.

**Comment by lumo76** [comment]
I have the same issue (on win 7, anaconda) but cannot migrate to Linux. Any suggestion?
