### ISSUE TITLE
errors_impl.NotFoundError: None.de; No such file or directory

### ISSUE THREAD

**Issue by prp20** [tensorflow/nmt#262]
Traceback (most recent call last):
  File "/home/prasad/anaconda3/envs/nmt/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/prasad/anaconda3/envs/nmt/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/prasad/nmt/nmt/nmt.py", line 605, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/prasad/anaconda3/envs/nmt/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 129, in run
    _sys.exit(main(argv))
  File "/home/prasad/nmt/nmt/nmt.py", line 598, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/prasad/nmt/nmt/nmt.py", line 591, in run_main
    train_fn(hparams, target_session=target_session)
  File "/home/prasad/nmt/nmt/train.py", line 303, in train
    sample_src_data = inference.load_data(dev_src_file)
  File "/home/prasad/nmt/nmt/inference.py", line 75, in load_data
    inference_data = f.read().splitlines()
  File "/home/prasad/anaconda3/envs/nmt/lib/python3.5/codecs.py", line 493, in read
    newdata = self.stream.read()
  File "/home/prasad/anaconda3/envs/nmt/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 119, in read
    self._preread_check()
  File "/home/prasad/anaconda3/envs/nmt/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/prasad/anaconda3/envs/nmt/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
**## # tensorflow.python.framework.errors_impl.NotFoundError: None.de; No such file or directory**

**Comment by mhsamavatian** [comment]
same error any comment?

**Comment by indrajeet95** [comment]
Same here.

**Comment by dandengAI** [comment]
same here

**Comment by frank-wei** [comment]
same here

**Comment by potato1996** [comment]
Hi guys, I guess the master branch is not fully compatible with python3. Try python2.7 instead?

**Comment by dadosch** [comment]
Has anyone found a solution?

**Comment by jefferson-guilherme-machado-barreto** [comment]
same here, I don't found the solution
