### ISSUE TITLE
When I enter the command line “Python -m nmt.nmt” at Pycharm Terminal, I get the following error:

### ISSUE THREAD

**Issue by Peng-Ru** [tensorflow/nmt#266]
My device ： Windows10 +tensorflow gpu1.6.0 +python 3.5.2+CUDA 9.0+CUDNN 7.0

C:\Users\pengru\Desktop\nmt-master>python -m nmt.nmt

F:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argume
nt of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np
.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
# Job id 0
Traceback (most recent call last):
  File "F:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pengru\Desktop\nmt-master\nmt\nmt.py", line 605, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\pengru\Desktop\nmt-master\nmt\nmt.py", line 598, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "C:\Users\pengru\Desktop\nmt-master\nmt\nmt.py", line 558, in run_main
    if not tf.gfile.Exists(out_dir): tf.gfile.MakeDirs(out_dir)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 255, in file_exi
sts
    pywrap_tensorflow.FileExists(compat.as_bytes(filename), status)
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\util\compat.py", line 67, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by tvtienit** [comment]
Have you solved this issue yet? I got the same problem while I ran the inference
