### ISSUE TITLE
TypeError: Expected binary or unicode string, got None

### ISSUE THREAD

**Issue by Fixa11** [tensorflow/nmt#267]
I am trying to train with

python -m nmt.nmt \
    --src=vi --tgt=en \
    --vocab_prefix=/tmp/nmt_data/vocab  \
    --train_prefix=/tmp/nmt_data/train \
    --dev_prefix=/tmp/nmt_data/tst2012  \
    --test_prefix=/tmp/nmt_data/tst2013 \
    --out_dir=/tmp/nmt_model \
    --num_train_steps=12000 \
    --steps_per_stats=100 \
    --num_layers=2 \
    --num_units=128 \
    --dropout=0.2 \
    --metrics=bleu

But I recevied the following error : 

# Job id 0
Traceback (most recent call last):
  File "C:\Users\josh\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\josh\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\josh\nmt\nmt\nmt.py", line 605, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\josh\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:\Users\josh\nmt\nmt\nmt.py", line 598, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "C:\Users\josh\nmt\nmt\nmt.py", line 558, in run_main
    if not tf.gfile.Exists(out_dir): tf.gfile.MakeDirs(out_dir)
  File "C:\Users\josh\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 253, in file_exists
    pywrap_tensorflow.FileExists(compat.as_bytes(filename), status)
  File "C:\Users\josh\Anaconda3\lib\site-packages\tensorflow\python\util\compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by mmuaz95** [comment]
I get the same error. Do you have any solutions?

**Comment by Luoice** [comment]
you have other solutions?

**Comment by Luoice** [comment]
I get the same error. Who can help me to solve the problem?

**Comment by Luoice** [comment]
thanks in advance.

**Comment by Luoice** [comment]
D:\>python D:/model_fish_detection/model_main.py train_dir=D:/model_fish_detection/result pipeline_config_path=D:/model_fish_detection/training/ssd_mobilenet_v1_coco.config checkpoint_dir=D:/model_fish_detection/pre_model/model.ckpt.data-00000-of-00001 add_postprocessing_op=true
error:TypeError: Expected binary or unicode string, got None

**Comment by Luoice** [comment]
(D:\swinstall\anaconda3) D:\>python D:/model_fish_detection/model_main.py train_dir=D:/model_fish_detection/result pipeline_config_path=D:/model_fish_detection/training/ssd_mobilenet_v1_coco.config checkpoint_dir=D:/model_fish_detection/pre_model/model.ckpt.data-00000-of-00001 add_postprocessing_op=true
Traceback (most recent call last):
  File "D:/model_fish_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "D:\swinstall\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:/model_fish_detection/model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "D:\swinstall\anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\model_lib.py", line 525, in create_estimator_and_inputs
    configs = get_configs_from_pipeline_file(pipeline_config_path)
  File "D:\swinstall\anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\config_util.py", line 93, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "D:\swinstall\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "D:\swinstall\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "D:\swinstall\anaconda3\lib\site-packages\tensorflow\python\util\compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by Luoice** [comment]
Who can help me to solve the problem?
