### ISSUE TITLE
issue with new data

### ISSUE THREAD

**Issue by acadTags** [tensorflow/nmt#268]
It says "empty line found at position 16.", but I could not find any empty lines in my file "vocab.content". How to solve this problem?

H:\nmt-master>python -m nmt.nmt \    --attention=scaled_luong \    --src=content --tgt=tag \    --vocab_prefix=H:\nmt-master\tmp\tag_annotation_data\vocab  \    --train_prefix=H:\nmt-master\tmp\tag_annotation_data\train \    --dev_prefix=H:\nmt-master\tmp\tag_annotation_data\dev  \    --test_prefix=H:\nmt-master\tmp\tag_annotation_data\test \    --out_dir=H:\nmt-master\tmp\tag_attention_model \    --num_train_steps=12000 \    --steps_per_stats=100 \    --num_layers=2 \    --num_units=128 \    --dropout=0.2 \    --metrics=bleu
C:\Program Files\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
# Job id 0
# Loading hparams from H:\nmt-master\tmp\tag_attention_model\hparams
  saving hparams to H:\nmt-master\tmp\tag_attention_model\hparams
  saving hparams to H:\nmt-master\tmp\tag_attention_model\best_bleu\hparams
  attention=scaled_luong
  attention_architecture=standard
  avg_ckpts=False
  batch_size=128
  beam_width=0
  best_bleu=0
  best_bleu_dir=H:\nmt-master\tmp\tag_attention_model\best_bleu
  check_special_token=True
  colocate_gradients_with_ops=True
  decay_scheme=
  dev_prefix=H:\nmt-master\tmp\tag_annotation_data\dev
  dropout=0.2
  embed_prefix=None
  encoder_type=uni
  eos=</s>
  epoch_step=0
  forget_bias=1.0
  infer_batch_size=32
  init_op=uniform
  init_weight=0.1
  learning_rate=1.0
  length_penalty_weight=0.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=['bleu']
  num_buckets=5
  num_decoder_layers=2
  num_decoder_residual_layers=0
  num_embeddings_partitions=0
  num_encoder_layers=2
  num_encoder_residual_layers=0
  num_gpus=1
  num_inter_threads=0
  num_intra_threads=0
  num_keep_ckpts=5
  num_layers=2
  num_train_steps=12000
  num_translations_per_input=1
  num_units=128
  optimizer=sgd
  out_dir=H:\nmt-master\tmp\tag_attention_model
  output_attention=True
  override_loaded_hparams=False
  pass_hidden_state=True
  random_seed=None
  residual=False
  sampling_temperature=0.0
  share_vocab=False
  sos=<s>
  src=content
  src_embed_file=
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=H:\nmt-master\tmp\tag_attention_model\vocab.content
  src_vocab_size=52497
  steps_per_external_eval=None
  steps_per_stats=100
  subword_option=
  test_prefix=H:\nmt-master\tmp\tag_annotation_data\test
  tgt=tag
  tgt_embed_file=
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=H:\nmt-master\tmp\tag_attention_model\vocab.tag
  tgt_vocab_size=3791
  time_major=True
  train_prefix=H:\nmt-master\tmp\tag_annotation_data\train
  unit_type=lstm
  vocab_prefix=H:\nmt-master\tmp\tag_annotation_data\vocab
  warmup_scheme=t2t
  warmup_steps=0
# creating train graph ...
  num_layers = 2, num_residual_layers=0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  learning_rate=1, warmup_steps=0, warmup_scheme=t2t
  decay_scheme=, start_decay_step=12000, decay_steps 0, decay_factor 1
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (52497, 128), /device:CPU:0
  embeddings/decoder/embedding_decoder:0, (3791, 128), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (128, 128),
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (384, 512), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (256, 128), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (128, 3791),
# creating eval graph ...
  num_layers = 2, num_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (52497, 128), /device:CPU:0
  embeddings/decoder/embedding_decoder:0, (3791, 128), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (128, 128),
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (384, 512), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (256, 128), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (128, 3791),
# creating infer graph ...
  num_layers = 2, num_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (52497, 128), /device:CPU:0
  embeddings/decoder/embedding_decoder:0, (3791, 128), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (128, 128),
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (384, 512), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (256, 512), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (512,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (256, 128), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (128, 3791),
# log_file=H:\nmt-master\tmp\tag_attention_model\log_1520678129
2018-03-10 10:35:31.083587: W C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1202] OP_REQUIRES failed at lookup_table_init_op.cc:145 : Invalid argument: Invalid content in H:\nmt-master\tmp\tag_attention_model\vocab.content: empty line found at position 16.
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid content in H:\nmt-master\tmp\tag_attention_model\vocab.content: empty line found at position 16.
         [[Node: string_to_index/hash_table/table_init = InitializeTableFromTextFileV2[delimiter="\t", key_index=-2, value_index=-1, vocab_size=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](string_to_index/hash_table, string_to_index/hash_table/table_init/asset_filepath)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\nmt-master\nmt\nmt.py", line 605, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "H:\nmt-master\nmt\nmt.py", line 598, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "H:\nmt-master\nmt\nmt.py", line 591, in run_main
    train_fn(hparams, target_session=target_session)
  File "H:\nmt-master\nmt\train.py", line 328, in train
    train_model.model, model_dir, train_sess, "train")
  File "H:\nmt-master\nmt\model_helper.py", line 572, in create_or_load_model
    session.run(tf.tables_initializer())
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid content in H:\nmt-master\tmp\tag_attention_model\vocab.content: empty line found at position 16.
         [[Node: string_to_index/hash_table/table_init = InitializeTableFromTextFileV2[delimiter="\t", key_index=-2, value_index=-1, vocab_size=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](string_to_index/hash_table, string_to_index/hash_table/table_init/asset_filepath)]]

Caused by op 'string_to_index/hash_table/table_init', defined at:
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\nmt-master\nmt\nmt.py", line 605, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "H:\nmt-master\nmt\nmt.py", line 598, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "H:\nmt-master\nmt\nmt.py", line 591, in run_main
    train_fn(hparams, target_session=target_session)
  File "H:\nmt-master\nmt\train.py", line 296, in train
    train_model = model_helper.create_train_model(model_creator, hparams, scope)
  File "H:\nmt-master\nmt\model_helper.py", line 80, in create_train_model
    src_vocab_file, tgt_vocab_file, hparams.share_vocab)
  File "H:\nmt-master\nmt\utils\vocab_utils.py", line 82, in create_vocab_tables
    src_vocab_file, default_value=UNK_ID)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\lookup_ops.py", line 1009, in index_table_from_file
    init, default_value, shared_name=shared_name, name=hash_table_scope)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\lookup_ops.py", line 285, in __init__
    super(HashTable, self).__init__(table_ref, default_value, initializer)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\lookup_ops.py", line 171, in __init__
    self._init = initializer.initialize(self)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\lookup_ops.py", line 529, in initialize
    name=scope)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_lookup_ops.py", line 298, in _initialize_table_from_text_file_v2
    vocab_size=vocab_size, delimiter=delimiter, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Invalid content in H:\nmt-master\tmp\tag_attention_model\vocab.content: empty line found at position 16.
         [[Node: string_to_index/hash_table/table_init = InitializeTableFromTextFileV2[delimiter="\t", key_index=-2, value_index=-1, vocab_size=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](string_to_index/hash_table, string_to_index/hash_table/table_init/asset_filepath)]]

**Comment by acadTags** [comment]
solved, just delete the vocab files generated in the "xxx_attention model" folder.

**Comment by NischalBhatewara** [comment]
hi, I'm getting the same error. deleting the output dir does not help. any other solutions?

**Comment by edugp** [comment]
I had a single space on one line of my vocab file, I removed it, removed the output directory, run again and it worked. Hope it helps!

**Comment by wuyongzheng** [comment]
> I had a single space on one line of my vocab file, I removed it, removed the output directory, run again and it worked. Hope it helps!

Apart from the regular space character, other kind of white spaces need to be removed as well, such as ideographic space character (U+3000)
