### ISSUE TITLE
Error when using multiple metrics

### ISSUE THREAD

**Issue by claudzhou** [tensorflow/nmt#27]
There seems to be a bug when using multiple metrics.
It exits with an error after outputting "# Best %s" % metrics...

Here's the error trackback:

...
  bleu dev: 0.0
  rouge dev: 0.0
  bleu test: 0.0
  rouge test: 0.0
# Best rouge, step 0 step-time 0.38 wps 9.17K, dev ppl 17190.87, dev bleu 0.0, dev rouge 0.0, test ppl 17190.47, test bleu 0.0, test rouge 0.0, Sun Jul 23 21:36:22 2017
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/xianda/nmt/nmt/nmt.py", line 478, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/xianda/nmt/env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/xianda/nmt/nmt/nmt.py", line 471, in main
    train.train(hparams)
  File "nmt/train.py", line 464, in train
    return (dev_scores, test_scores, dev_ppl, test_ppl, global_step)
UnboundLocalError: local variable 'dev_scores' referenced before assignment

**Comment by oahziur** [comment]
@claudzhou Do you still have the problem after a pull, I think this b44d233da2f85461a6a58ed174c377e2057082ae should fix the error?
