### ISSUE TITLE
Can't run the training process correctly

### ISSUE THREAD

**Issue by MarkCongMa** [tensorflow/nmt#313]
when I want to run the following codes in my terminal,
`
python -m nmt.nmt \
    --src=vi --tgt=en \
    --vocab_prefix=/tmp/nmt_data/vocab  \
    --train_prefix=/tmp/nmt_data/train \
    --dev_prefix=/tmp/nmt_data/tst2012  \
    --test_prefix=/tmp/nmt_data/tst2013 \
    --out_dir=/tmp/nmt_model \
    --num_train_steps=12000 \
    --steps_per_stats=100 \
    --num_layers=2 \
    --num_units=128 \
    --dropout=0.2 \
    --metrics=bleu
`

The system gave me the information like:

`
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "nmt.py", line 28, in <module>
    from . import inference
ValueError: Attempted relative import in non-package
`

**_I don't know what happened and I really wonder how to fix it, can anyone help me? Thanks so much._**

**Comment by liuguojun** [comment]
I have the same problem

**Comment by liuguojun** [comment]
I solved this problem. Go to the parent directory and run this command. Everything is ok now

**Comment by VictorZhang2014** [comment]
I've already got to know why it runs with `python -m nmt.nmt `?  The first `nmt` is the directory and second `nmt` that actually is `nmt.py`. So there is a little perplexity to most programmers I think. 

Thank you! @liuguojun
