### ISSUE TITLE
model_test failures

### ISSUE THREAD

**Issue by ranjita-naik** [tensorflow/nmt#405]
FAIL: testBeamSearchAttentionModel (__main__.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/nmt/nmt/model_test.py", line 973, in testBeamSearchAttentionModel
    infer_m, sess, assert_top_k_sentence, 'BeamSearchAttentionModel')
  File "D:/nmt/nmt/model_test.py", line 300, in _assertBeamSearchOutputs
    self.assertEqual(expected_sentence, sentence)
AssertionError: '' != b''

======================================================================
FAIL: testBeamSearchBasicModel (__main__.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
'UniEncoderStandardAttentionArchitecture/predict_count': 11}
  File "D:/nmt/nmt/model_test.py", line 955, in testBeamSearchBasicModel
ModelTest - actual_infer_values: 
    infer_m, sess, assert_top_k_sentence, 'BeamSearchBasicModel')
{'AttentionMechanismBahdanau/logits_sum': -0.027910301,
  File "D:/nmt/nmt/model_test.py", line 300, in _assertBeamSearchOutputs
 'AttentionMechanismLuong/logits_sum': -0.027987663,
    self.assertEqual(expected_sentence, sentence)
 'AttentionMechanismNormedBahdanau/logits_sum': -0.02793302,
AssertionError: 'b b b b' != b'b b b b'
 'AttentionMechanismScaledLuong/logits_sum': -0.0278839,

 'GNMTModel_gnmt/logits_sum': -1.1100831,
======================================================================
 'GNMTModel_gnmt_v2/logits_sum': -1.1117681,
FAIL: testBeamSearchGNMTModel (__main__.ModelTest)
 'NoAttentionNoResidualUniEncoder/logits_sum': -1.0780617,
----------------------------------------------------------------------
 'NoAttentionResidualBiEncoder/logits_sum': -2.843052,
Traceback (most recent call last):
 'UniEncoderStandardAttentionArchitecture/logits_sum': -0.028336454}
  File "D:/nmt/nmt/model_test.py", line 990, in testBeamSearchGNMTModel
ModelTest - actual_beam_sentences: 
    infer_m, sess, assert_top_k_sentence, 'BeamSearchGNMTModel')
{'BeamSearchAttentionModel: batch 0 of beam 0': b'',
  File "D://nmt/nmt/model_test.py", line 300, in _assertBeamSearchOutputs
 'BeamSearchBasicModel: batch 0 of beam 0': b'b b b b',
    self.assertEqual(expected_sentence, sentence)
 'BeamSearchGNMTModel: batch 0 of beam 0': b''}
AssertionError: '' != b''

----------------------------------------------------------------------
Ran 16 tests in 209.242s

FAILED (failures=3)

Process finished with exit code 1

**Comment by ranjita-naik** [comment]
Have created for a PR for fixing the error https://github.com/tensorflow/nmt/pull/401
