### ISSUE TITLE
Unit test failure for GNMT model

### ISSUE THREAD

**Issue by Rithesh-K** [tensorflow/nmt#442]
I was trying to test the GNMT model using the testcases written in the model_test.py file when I found this:

```
Rithesh-K:nmt ritheshk$ python3.7 -m unittest nmt.model_test.ModelTest.testGNMTModelV2
2019-05-26 14:50:28.684608: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job ps -> {}
2019-05-26 14:50:28.684641: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job worker -> {0 -> localhost:23950}
2019-05-26 14:50:28.685253: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:23950
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/lookup_ops.py:1137: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
EModelTest - actual_vars_values: 
{}
ModelTest - actual_train_values: 
{}
ModelTest - actual_eval_values: 
{}
ModelTest - actual_infer_values: 
{}
ModelTest - actual_beam_sentences: 
{}

======================================================================
ERROR: testGNMTModelV2 (nmt.model_test.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ritheshk/Git/nmt/nmt/model_test.py", line 1021, in testGNMTModelV2
    self._testGNMTModel("gnmt_v2")
  File "/Users/ritheshk/Git/nmt/nmt/model_test.py", line 978, in _testGNMTModel
    gnmt_model.GNMTModel, hparams, sess
  File "/Users/ritheshk/Git/nmt/nmt/model_test.py", line 273, in _createTestTrainModel
    hparams, train_mode
  File "/Users/ritheshk/Git/nmt/nmt/utils/common_test_utils.py", line 134, in create_test_iterator
    num_buckets=hparams.num_buckets,
  File "/Users/ritheshk/Git/nmt/nmt/utils/iterator_utils.py", line 210, in get_iterator
    (src_dataset, tgt_dataset, conv_dataset, weights_dataset)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1471, in zip
    return DatasetV1Adapter(DatasetV2.zip(datasets))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 610, in zip
    return ZipDataset(datasets)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2248, in __init__
    raise TypeError(message)
TypeError: The argument to `Dataset.zip()` must be a nested structure of `Dataset` objects.

----------------------------------------------------------------------
Ran 1 test in 0.029s

FAILED (errors=1)
```

**Comment by Rithesh-K** [comment]
Sorry. This was a mistake from my side
