### ISSUE TITLE
from nmt import nmt

### ISSUE THREAD

**Issue by ppowdderr** [tensorflow/nmt#447]
Traceback (most recent call last):
  File "F:/AI/RedditChatBot/nmt-chatbot-master/train.py", line 8, in <module>
    from nmt import nmt
  File "F:\AI\RedditChatBot\nmt-chatbot-master\nmt\nmt.py", line 28, in <module>
    from . import inference
  File "F:\AI\RedditChatBot\nmt-chatbot-master\nmt\inference.py", line 25, in <module>
    from . import gnmt_model
  File "F:\AI\RedditChatBot\nmt-chatbot-master\nmt\gnmt_model.py", line 261, in <module>
    class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'

i have python 3.5.0
i have downloaded the new nmt file and replaced it with old one
and still have this problem. Please help

**Comment by maharajbrahma** [comment]
Please try installing other version of tensorflow, this framework is not written for tensorflow v2.0.

**Comment by nashid** [comment]
Is there any plan to update this framework for the latest version of tensorflow?

If not what is the preferred framework?
