### ISSUE TITLE
Failure during inference

### ISSUE THREAD

**Issue by emeiri-intel** [tensorflow/nmt#58]
Hi,

I followed the installation instructions (installed TF 1.2.1, cloned the repo, 'ran nmt/scripts/download_iwslt15.sh /tmp/nmt_data' and downloaded the pre trained weight files).

I ran the following command which is specified in the envi_model_1 README:

python -m nmt.nmt     --src=en --tgt=vi  \
   --ckpt=models/envi_model_1/translate.ckpt  
   --hparams_path=nmt/standard_hparams/iwslt15.json   
  --out_dir=/tmp/envi  
   --vocab_prefix=/tmp/nmt_data/vocab  
   --inference_input_file=/tmp/nmt_data/tst2013.en   
  --inference_output_file=/tmp/envi/output_infer     --inference_ref_file=/tmp/nmt_data/tst2013.vi 

The result was:
# Job id 0
# Loading hparams from /tmp/envi/hparams
# Loading standard hparams from nmt/standard_hparams/iwslt15.json
  saving hparams to /tmp/envi/hparams
  saving hparams to /tmp/envi/best_bleu/hparams
  attention=scaled_luong
  attention_architecture=standard
  batch_size=128
  beam_width=10
  best_bleu=0
  best_bleu_dir=/tmp/envi/best_bleu
  bpe_delimiter=None
  colocate_gradients_with_ops=True
  decay_factor=0.5
  decay_steps=1000
  dev_prefix=None
  dropout=0.2
  encoder_type=bi
  eos=</s>
  epoch_step=0
  forget_bias=1.0
  infer_batch_size=32
  init_weight=0.1
  learning_rate=1.0
  length_penalty_weight=0.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=[u'bleu']
  num_buckets=5
  num_gpus=1
  num_layers=2
  num_residual_layers=0
  num_train_steps=12000
  num_units=512
  optimizer=sgd
  out_dir=/tmp/envi
  pass_hidden_state=True
  random_seed=None
  residual=False
  share_vocab=False
  sos=<s>
  source_reverse=False
  src=vi
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=nmt_data/vocab.vi
  src_vocab_size=7709
  start_decay_step=8000
  steps_per_external_eval=None
  steps_per_stats=100
  test_prefix=None
  tgt=en
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=nmt_data/vocab.en
  tgt_vocab_size=17191
  time_major=True
  train_prefix=None
  unit_type=lstm
  vocab_prefix=nmt_data/vocab
# creating infer graph ...
  num_bi_layers = 1, num_bi_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  start_decay_step=8000, learning_rate=1, decay_steps 1000,decay_factor 0.5
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (7709, 512), 
  embeddings/decoder/embedding_decoder:0, (17191, 512), 
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (1024, 512), 
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (1536, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (1536, 512), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (512, 17191), 
2017-08-09 16:35:38.750263: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-09 16:35:38.750287: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-09 16:35:38.750295: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-09 16:35:38.750303: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-09 16:35:38.750309: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
models/envi_model_1/translate.ckpt
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 483, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 476, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 455, in run_main
    trans_file, hparams, num_workers, jobid)
  File "nmt/inference.py", line 165, in inference
    hparams)
  File "nmt/inference.py", line 191, in single_worker_inference
    infer_model.model, ckpt, sess, "infer")
  File "nmt/model_helper.py", line 207, in load_model
    model.saver.restore(session, ckpt)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,17191] rhs shape= [512,7709]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/output_projection/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](dynamic_seq2seq/decoder/output_projection/kernel, save/RestoreV2_8)]]

Caused by op u'save/Assign_8', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 483, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 476, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 455, in run_main
    trans_file, hparams, num_workers, jobid)
  File "nmt/inference.py", line 157, in inference
    single_cell_fn)
  File "nmt/inference.py", line 79, in create_infer_model
    single_cell_fn=single_cell_fn)
  File "nmt/attention_model.py", line 55, in __init__
    single_cell_fn=single_cell_fn)
  File "nmt/model.py", line 167, in __init__
    self.saver = tf.train.Saver(tf.global_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 271, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,17191] rhs shape= [512,7709]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/output_projection/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](dynamic_seq2seq/decoder/output_projection/kernel, save/RestoreV2_8)]]

Any idea what the problem is?

Thanks a lot,

Etay

**Comment by oahziur** [comment]
Did you reuse your out dir? 

The printed hparams shows the `src=vi` and `tgt=en`, but the FLAG you passed in is `src=en` and `tgt=vi`, I wonder if it restore the hyper parameter from your previous command.

**Comment by emeiri-intel** [comment]
Thanks, Zhao. I deleted the our dir and reversed the params you mentioned. Looks like the error didn't change much. Here's the updated output:

python -m nmt.nmt --src=vi --tgt=en --ckpt=models/envi_model_1/translate.ckpt --hparams_path=nmt/standard_hparams/iwslt15.json --out_dir=/tmp/envi --vocab_prefix=/tmp/nmt_data/vocab --inference_input_file=/tmp/nmt_data/tst2013.vi --inference_output_file=/tmp/envi/output_infer --inference_ref_file=/tmp/nmt_data/tst2013.en
# Job id 0
# Loading standard hparams from nmt/standard_hparams/iwslt15.json
# hparams:
  src=vi
  tgt=en
  train_prefix=None
  dev_prefix=None
  test_prefix=None
  out_dir=/tmp/envi
# Vocab file /tmp/nmt_data/vocab.vi exists
# Vocab file /tmp/nmt_data/vocab.en exists
  saving hparams to /tmp/envi/hparams
  saving hparams to /tmp/envi/best_bleu/hparams
  attention=scaled_luong
  attention_architecture=standard
  batch_size=128
  beam_width=10
  best_bleu=0
  best_bleu_dir=/tmp/envi/best_bleu
  bpe_delimiter=None
  colocate_gradients_with_ops=True
  decay_factor=0.5
  decay_steps=1000
  dev_prefix=None
  dropout=0.2
  encoder_type=bi
  eos=</s>
  epoch_step=0
  forget_bias=1.0
  infer_batch_size=32
  init_weight=0.1
  learning_rate=1.0
  length_penalty_weight=0.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=[u'bleu']
  num_buckets=5
  num_gpus=1
  num_layers=2
  num_residual_layers=0
  num_train_steps=12000
  num_units=512
  optimizer=sgd
  out_dir=/tmp/envi
  pass_hidden_state=True
  random_seed=None
  residual=False
  share_vocab=False
  sos=<s>
  source_reverse=False
  src=vi
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=/tmp/nmt_data/vocab.vi
  src_vocab_size=7709
  start_decay_step=8000
  steps_per_external_eval=None
  steps_per_stats=100
  test_prefix=None
  tgt=en
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=/tmp/nmt_data/vocab.en
  tgt_vocab_size=17191
  time_major=True
  train_prefix=None
  unit_type=lstm
  vocab_prefix=/tmp/nmt_data/vocab
# creating infer graph ...
  num_bi_layers = 1, num_bi_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  start_decay_step=8000, learning_rate=1, decay_steps 1000,decay_factor 0.5
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (7709, 512), 
  embeddings/decoder/embedding_decoder:0, (17191, 512), 
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (1024, 512), 
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (1536, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (1536, 512), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (512, 17191), 
2017-08-10 10:41:40.365539: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-10 10:41:40.365556: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-10 10:41:40.365562: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-10 10:41:40.365566: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-10 10:41:40.365569: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
models/envi_model_1/translate.ckpt
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 483, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 476, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 455, in run_main
    trans_file, hparams, num_workers, jobid)
  File "nmt/inference.py", line 165, in inference
    hparams)
  File "nmt/inference.py", line 191, in single_worker_inference
    infer_model.model, ckpt, sess, "infer")
  File "nmt/model_helper.py", line 207, in load_model
    model.saver.restore(session, ckpt)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,17191] rhs shape= [512,7709]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/output_projection/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](dynamic_seq2seq/decoder/output_projection/kernel, save/RestoreV2_8)]]

Caused by op u'save/Assign_8', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 483, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 476, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/emeiri/work/nmt/nmt/nmt.py", line 455, in run_main
    trans_file, hparams, num_workers, jobid)
  File "nmt/inference.py", line 157, in inference
    single_cell_fn)
  File "nmt/inference.py", line 79, in create_infer_model
    single_cell_fn=single_cell_fn)
  File "nmt/attention_model.py", line 55, in __init__
    single_cell_fn=single_cell_fn)
  File "nmt/model.py", line 167, in __init__
    self.saver = tf.train.Saver(tf.global_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 271, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,17191] rhs shape= [512,7709]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/output_projection/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](dynamic_seq2seq/decoder/output_projection/kernel, save/RestoreV2_8)]]

**Comment by oahziur** [comment]
@emeiri-intel 

I meant delete the out dir first, and then try the same command in the installation instructions again (don't revert src and tgt). Let me know if this works. Thanks.

**Comment by emeiri-intel** [comment]
Now it works. Turns out that in the last few days some checkin fixed a problem. After pulling the latest version the above issue was resolved.

Thanks!
