### ISSUE TITLE
Error while training the baseline model

### ISSUE THREAD

**Issue by PasinduTennage** [tensorflow/nmt#72]
I get the following error while testing with the baseline model. (Sequence to Sequence model example in the Readme)

2017-08-21 22:22:40.341397: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.en is already initialized.
2017-08-21 22:22:40.341398: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.en is already initialized.
2017-08-21 22:22:40.343065: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.vi is already initialized.
b'  loaded infer model parameters from E:\\\\NMT\\\\dataset\\translate.ckpt-1000, time 0.16s'
b'  # 882'
b'    src: v\xe1\xbb\x9bi g\xe1\xba\xa7n 200 tri\xe1\xbb\x87u l\xc6\xb0\xe1\xbb\xa3t xem .'
b'    ref: It &apos;s been seen nearly 200 million times this year .'
b"    nmt: b'So , I &apos;m going to be a lot of <unk> . </s>'"
2017-08-21 22:22:40.463611: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.vi is already initialized.
2017-08-21 22:22:40.464123: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.en is already initialized.
b'  loaded eval model parameters from E:\\\\NMT\\\\dataset\\translate.ckpt-1000, time 0.07s'
2017-08-21 22:22:42.147353: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\framework\op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]
2017-08-21 22:22:42.147358: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\framework\op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]
  eval dev: perplexity 108.59, time 1s, Mon Aug 21 22:22:42 2017.
2017-08-21 22:22:43.665650: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\framework\op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]
  eval test: perplexity 123.91, time 1s, Mon Aug 21 22:22:43 2017.
2017-08-21 22:22:53.950453: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\framework\op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]
2017-08-21 22:22:53.950634: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\framework\op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]
2017-08-21 22:22:53.950999: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\framework\op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]
b'# Finished an epoch, step 1043. Perform external evaluation'
2017-08-21 22:22:53.997090: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.vi is already initialized.
2017-08-21 22:22:53.997847: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.en is already initialized.
2017-08-21 22:22:53.997869: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.en is already initialized.
b'  loaded infer model parameters from E:\\\\NMT\\\\dataset\\translate.ckpt-1000, time 0.05s'
b'  # 1544'
b'    src: T\xc3\xb4i ho\xc3\xa0n to\xc3\xa0n kh\xc3\xb4ng c\xc3\xb3 g\xc3\xac khu\xe1\xba\xa5t t\xe1\xba\xa5t ph\xe1\xba\xa3i che d\xe1\xba\xa5u .'
b'    ref: Because I have nothing to hide . &quot;'
b"    nmt: b'So , I &apos;m going to do this . </s>'"
2017-08-21 22:22:54.084113: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.vi is already initialized.
2017-08-21 22:22:54.084674: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.en is already initialized.
2017-08-21 22:22:54.084728: W c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\kernels\lookup_table_init_op.cc:347] Table trying to initialize from file E:/NMT/dataset/voca
b.en is already initialized.
b'  loaded infer model parameters from E:\\\\NMT\\\\dataset\\translate.ckpt-1000, time 0.05s'
b'# External evaluation, global step 1000'
b'  decoding to output E:\\\\NMT\\\\dataset\\output_dev.'
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\NMT\nmt\nmt\train.py", line 352, in train
    step_result = loaded_train_model.train(train_sess)
  File "E:\NMT\nmt\nmt\model.py", line 194, in train
    self.batch_size])
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\NMT\nmt\nmt\nmt.py", line 492, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:\NMT\nmt\nmt\nmt.py", line 485, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "E:\NMT\nmt\nmt\nmt.py", line 478, in run_main
    train_fn(hparams)
  File "E:\NMT\nmt\nmt\train.py", line 277, in train
    single_cell_fn)
  File "E:\NMT\nmt\nmt\train.py", line 80, in create_train_model
    skip_count=skip_count_placeholder)
  File "E:\NMT\nmt\nmt\utils\iterator_utils.py", line 201, in get_iterator
    batched_iter.get_next())
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\data\python\ops\dataset_ops.py", line 247, in get_next
    name=name))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 254, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1,-1], [-1,-1], [-1], [-1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/repli
ca:0/task:0/cpu:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\NMT\nmt\nmt\nmt.py", line 492, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:\NMT\nmt\nmt\nmt.py", line 485, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "E:\NMT\nmt\nmt\nmt.py", line 478, in run_main
    train_fn(hparams)
  File "E:\NMT\nmt\nmt\train.py", line 367, in train
    hparams, summary_writer)
  File "E:\NMT\nmt\nmt\train.py", line 214, in run_external_eval
    save_on_best=save_best_dev)
  File "E:\NMT\nmt\nmt\train.py", line 554, in _external_eval
    decode=decode)
  File "E:\NMT\nmt\nmt\utils\nmt_utils.py", line 66, in decode_and_evaluate
    trans_f.write(("%s\n" % translation).decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'

**Comment by PasinduTennage** [comment]
Remove " .decode("utf-8") " from line 66 in utils\nmt_utils.py
