### ISSUE TITLE
Cannot execute "python -m nmt.nmt ..." for de to en

### ISSUE THREAD

**Issue by bingq** [tensorflow/nmt#74]
After downloading through the sh, failed to execute the following on Ubuntu (Python 2.7)
---------------------------------------
python -m nmt.nmt \
    --src=de --tgt=en \
    --ckpt=/path/to/checkpoint/translate.ckpt \
    --hparams_path=nmt/standard_hparams/wmt16_gnmt_4_layer.json \
    --out_dir=/tmp/deen_gnmt \
    --vocab_prefix=/tmp/wmt16/vocab.bpe.32000 \
    --inference_input_file=/tmp/wmt16/newstest2014.tok.bpe.32000.de \
    --inference_output_file=/tmp/deen_gnmt/output_infer \
    --inference_ref_file=/tmp/wmt16/newstest2014.tok.bpe.32000.en
---------------------------------------
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  ResidualWrapper  DeviceWrapper, device=/gpu:0
  cell 2  LSTM, forget_bias=1  ResidualWrapper  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 2  LSTM, forget_bias=1  ResidualWrapper  DeviceWrapper, device=/gpu:0
  cell 3  LSTM, forget_bias=1  ResidualWrapper  DeviceWrapper, device=/gpu:0
  start_decay_step=170000, learning_rate=1, decay_steps 17000,decay_factor 0.5
# Trainable variables
  embeddings/encoder/embedding_encoder:0, (36548, 1024),
  embeddings/decoder/embedding_decoder:0, (36548, 1024),
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/kernel:0, (2048, 4096), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/kernel:0, (2048, 4096), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (3072, 4096), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (2048, 4096), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_2/basic_lstm_cell/kernel:0, (2048, 4096), /device:GPU:0
  dynamic_seq2seq/encoder/rnn/multi_rnn_cell/cell_2/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (1024, 1024),
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0_attention/attention/basic_lstm_cell/kernel:0, (3072, 4096), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0_attention/attention/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0_attention/attention/bahdanau_attention/query_layer/kernel:0, (1024, 1024),
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0_attention/attention/bahdanau_attention/attention_v:0, (1024,),
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0_attention/attention/bahdanau_attention/attention_g:0, (),
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_0_attention/attention/bahdanau_attention/attention_b:0, (1024,),
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (3072, 4096), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_2/basic_lstm_cell/kernel:0, (3072, 4096), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_2/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_3/basic_lstm_cell/kernel:0, (3072, 4096), /device:GPU:0
  dynamic_seq2seq/decoder/multi_rnn_cell/cell_3/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (1024, 36548),
2017-08-22 01:24:32.892782: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 01:24:32.892868: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 01:24:32.892902: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 01:24:34.432269: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432421: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432655: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432756: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432789: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432536: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432885: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432914: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.432659: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433219: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433268: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433312: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433355: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433561: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433606: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433648: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433689: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.433903: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.434175: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.434380: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.434582: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.434945: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.435726: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.435878: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.436025: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.436328: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
2017-08-22 01:24:34.436447: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/nmt/nmt/nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/nmt/nmt/nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/root/nmt/nmt/nmt.py", line 467, in run_main
    trans_file, hparams, num_workers, jobid)
  File "nmt/inference.py", line 165, in inference
    hparams)
  File "nmt/inference.py", line 191, in single_worker_inference
    infer_model.model, ckpt, sess, "infer")
  File "nmt/model_helper.py", line 235, in load_model
    model.saver.restore(session, ckpt)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/nmt/nmt/nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/nmt/nmt/nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/root/nmt/nmt/nmt.py", line 467, in run_main
    trans_file, hparams, num_workers, jobid)
  File "nmt/inference.py", line 157, in inference
    single_cell_fn)
  File "nmt/inference.py", line 79, in create_infer_model
    single_cell_fn=single_cell_fn)
  File "nmt/gnmt_model.py", line 54, in __init__
    single_cell_fn=single_cell_fn)
  File "nmt/attention_model.py", line 55, in __init__
    single_cell_fn=single_cell_fn)
  File "nmt/model.py", line 167, in __init__
    self.saver = tf.train.Saver(tf.global_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /path/to/checkpoint/translate.ckpt: Not found: /path/to/checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
---------------------------------------------------------

Anything I can do for this error ? thank you !

**Comment by bastings** [comment]
`--ckpt=/path/to/checkpoint/translate.ckpt `

this needs to point to an actual checkpoint, so you need to modify the path there.

**Comment by bingq** [comment]
Thanks Joost.
