### ISSUE TITLE
Failed train the GNMT WMT German-English model as suggested in example 

### ISSUE THREAD

**Issue by bingq** [tensorflow/nmt#75]
trying to train with the following example command after downloading with "nmt/scripts/wmt16_en_de.sh /tmp/wmt16" successfully : 

python -m nmt.nmt \
    --src=de --tgt=en \
    --hparams_path=nmt/standard_hparams/wmt16_gnmt_4_layer.json \
    --out_dir=/tmp/deen_gnmt \
    --vocab_prefix=/tmp/wmt16/vocab.bpe.32000 \
    --train_prefix=/tmp/wmt16/train.tok.clean.bpe.32000 \
    --dev_prefix=/tmp/wmt16/newstest2013.tok.bpe.32000 \
    --test_prefix=/tmp/wmt16/newstest2015.tok.bpe.32000

However got the following failure from the very beginning: 

[2017-08-22 17:48:12]    dynamic_seq2seq/decoder/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
[2017-08-22 17:48:12]    dynamic_seq2seq/decoder/multi_rnn_cell/cell_2/basic_lstm_cell/kernel:0, (3072, 4096), /device:GPU:0
[2017-08-22 17:48:12]    dynamic_seq2seq/decoder/multi_rnn_cell/cell_2/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
[2017-08-22 17:48:12]    dynamic_seq2seq/decoder/multi_rnn_cell/cell_3/basic_lstm_cell/kernel:0, (3072, 4096), /device:GPU:0
[2017-08-22 17:48:12]    dynamic_seq2seq/decoder/multi_rnn_cell/cell_3/basic_lstm_cell/bias:0, (4096,), /device:GPU:0
[2017-08-22 17:48:12]    dynamic_seq2seq/decoder/output_projection/kernel:0, (1024, 36548), 
[2017-08-22 17:48:12]  Traceback (most recent call last):
[2017-08-22 17:48:12]    File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
[2017-08-22 17:48:12]      "__main__", fname, loader, pkg_name)
[2017-08-22 17:48:12]    File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
[2017-08-22 17:48:12]      exec code in run_globals
[2017-08-22 17:48:12]    File "/root/nmt/nmt/nmt.py", line 495, in <module>
[2017-08-22 17:48:12]      tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
[2017-08-22 17:48:12]    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
[2017-08-22 17:48:12]      _sys.exit(main(_sys.argv[:1] + flags_passthrough))
[2017-08-22 17:48:12]    File "/root/nmt/nmt/nmt.py", line 488, in main
[2017-08-22 17:48:12]      run_main(FLAGS, default_hparams, train_fn, inference_fn)
[2017-08-22 17:48:12]    File "/root/nmt/nmt/nmt.py", line 481, in run_main
[2017-08-22 17:48:12]      train_fn(hparams, target_session=target_session)
[2017-08-22 17:48:12]    File "nmt/train.py", line 292, in train
[2017-08-22 17:48:12]      sample_src_data = inference.load_data(dev_src_file)
[2017-08-22 17:48:12]    File "nmt/inference.py", line 128, in load_data
[2017-08-22 17:48:12]      inference_data = f.read().splitlines()
[2017-08-22 17:48:12]    File "/usr/lib/python2.7/codecs.py", line 468, in read
[2017-08-22 17:48:12]      newdata = self.stream.read()
[2017-08-22 17:48:12]    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
[2017-08-22 17:48:12]      self._preread_check()
[2017-08-22 17:48:12]    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
[2017-08-22 17:48:12]      compat.as_bytes(self.__name), 1024 * 512, status)
[2017-08-22 17:48:12]    File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
[2017-08-22 17:48:12]      self.gen.next()
[2017-08-22 17:48:12]    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
[2017-08-22 17:48:12]      pywrap_tensorflow.TF_GetCode(status))
[2017-08-22 17:48:12]  tensorflow.python.framework.errors_impl.NotFoundError: None.de

Pasting full logs in attached file
[fulllog.txt](https://github.com/tensorflow/nmt/files/1241367/fulllog.txt)

**Comment by oahziur** [comment]
@bingq  It seems there are existing hparam file which has train_prefix=None and dev_prefix=None in your out_dir. Training with a fresh out_dir should resolve the problem.

**Comment by bingq** [comment]
Thank you. It works !
