### ISSUE TITLE
List Index out of Range Error

### ISSUE THREAD

**Issue by ArmageddonKnight** [tensorflow/nmt#86]
Hi,

Sorry but I have some problem in running the large-scale data file (English-German), I first downloaded the dataset using the command

    nmt/scripts/wmt16_en_de.sh /tmp/wmt16

and then I ran the program using the configuration

```
python -m nmt.nmt  \
--src=en --tgt=de     \
--hparams_path=nmt/standard_hparams/wmt16_gnmt_4_layer.json     \
--out_dir=/tmp/deen_gnmt     \
--vocab_prefix=/tmp/wmt16/vocab.bpe.32000     \
--train_prefix=/tmp/wmt16/train.tok.clean.bpe.32000     \
--dev_prefix=/tmp/wmt16/newstest2013.tok.bpe.32000     \
--test_prefix=/tmp/wmt16/newstest2015.tok.bpe.32000
```

but I got the following error

```
  # 1123
    src: Außerdem werden die Hy@@ m@@ nen zusammen in einer Direkt@@ sch@@ altung vom Tschechischen Fernsehen live übertragen .
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bojian/nmt/nmt/nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/bojian/nmt/nmt/nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/bojian/nmt/nmt/nmt.py", line 481, in run_main
    train_fn(hparams, target_session=target_session)
  File "nmt/train.py", line 215, in train
    sample_tgt_data)
  File "nmt/train.py", line 137, in run_full_eval
    sample_src_data, sample_tgt_data)
  File "nmt/train.py", line 51, in run_sample_decode
    infer_model.batch_size_placeholder, summary_writer)
  File "nmt/train.py", line 416, in _sample_decode
    utils.print_out("    ref: %s" % tgt_data[decode_id])
IndexError: list index out of range
```
Could you please kindly help me with this issue? Thank you so much.

**Comment by angtany** [comment]
Please suggest the solution of the above problem. I am facing the same.
