### ISSUE TITLE
Bidirectional RNN error

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/nmt#88]
I am writing my custom code and I have taken the source from **_build_bidirectional_rnn** to add this functionality. When **num_layers** is less than 4, I get the following error:

```
Traceback (most recent call last):
  File "example2.py", line 70, in <module>
    main()
  File "example2.py", line 51, in main
    test_record='test.tfrecords'
  File "vsr.py", line 76, in __init__
    self._create_models()
  File "vsr.py", line 192, in _create_models
    mode='train')
  File "vsr.py", line 161, in _make_model
    hparams=self._hparams
  File "model.py", line 37, in __init__
    self._init_decoder()
  File "model.py", line 407, in _init_decoder
    self._build_decoder_train()
  File "model.py", line 242, in _build_decoder_train
    self._decoder_train)
  File "/usr/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 286, in dynamic_decode
    swap_memory=swap_memory)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 234, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/usr/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 139, in step
    cell_outputs, cell_state = self._cell(inputs, state)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 938, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 866, in __call__
    return self._cell(inputs, state, scope=scope)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 774, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 548, in call
    (c_prev, m_prev) = state
ValueError: not enough values to unpack (expected 2, got 1)
```

num_bi_layers can be 0 in the nmt tutorial, so I also take a max(1, int(num_layers / 2) )
Yet, everything that falls in the num_bi_layers == 1 (encoder_state = bi_encoder_state) branch seems to incompatible with the decoder.

Can see that encoder_state in the first case is a **tuple of tuples** of LSTMStateTuple, while for more than 2 bi_layers it is a tuple of LSTMStateTuple (and this case works fine).

Could you please suggest a way to fix this error?
Thank you

**Comment by JustinLin610** [comment]
I also met this problem...

**Comment by georgesterpu** [comment]
Hi @JustinLin610,
I was able to fix this by avoiding to call MultiRNNCell on a single cell, please see [this line](https://github.com/tensorflow/nmt/blob/05f8cc1e1273cea4348b7d3033a0d00fe8e2b061/nmt/model_helper.py#L393).
