### ISSUE TITLE
wmt16_en_de.sh crashed with "Illegal byte sequence"

### ISSUE THREAD

**Issue by RockfordWei** [tensorflow/nmt#91]
`wmt16_en_de.sh` runs partially then crashed:

```
Cloning into '/tmp/wmt16/subword-nmt'...
...
Learning BPE with merge_ops=32000. This may take a while...
Apply BPE with merge_ops=32000 to tokenized files...
... (many tok files here, skipped.)
/tmp/wmt16/newstest2016.tok.clean.bpe.32000.de
/tmp/wmt16/train.tok.clean.bpe.32000.de
cut: stdin: Illegal byte sequence
Traceback (most recent call last):
  File "/tmp/wmt16/subword-nmt/get_vocab.py", line 13, in <module>
    print(key+" "+ str(f))
IOError: [Errno 32] Broken pipe
```

Considering it took such a long time and almost done, how to fix the script and resume the whole procedure???

Thanks.

**Comment by RockfordWei** [comment]
This only happens on Mac OS X. Everything is fine on Ubuntu 16.04 LTS.

**Comment by saikiranbandaru** [comment]
Has there been any fix for this? I've been getting the same error. Running this on macOS Sierra.

```
/tmp/wmt16/train.tok.clean.bpe.32000.de
/tmp/wmt16/subword-nmt/get_vocab.py:60: DeprecationWarning: this script's location has moved to /tmp/wmt16/subword-nmt/subword_nmt. This symbolic link will be removed in a future version. Please point to the new location, or install the package and use the command 'subword-nmt'
  DeprecationWarning
cut: stdin: Illegal byte sequence
Traceback (most recent call last):
  File "/tmp/wmt16/subword-nmt/get_vocab.py", line 82, in <module>
    get_vocab(args.input, args.output)
  File "/tmp/wmt16/subword-nmt/get_vocab.py", line 50, in get_vocab
    vocab_file.write(key+" "+ str(f) + "\n")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 370, in write
    self.stream.write(data)
IOError: [Errno 32] Broken pipe
```
