### ISSUE TITLE
DivideByzero error before parameter save

### ISSUE THREAD

**Issue by aaryavrate** [tensorflow/nmt#95]
Hi,

I am facing this error at 1000th step when parameters are saved. At 900th step, the value is 4018. Here is the log.

` loaded eval model parameters from vmr_model/translate.ckpt-1000, time 0.07s
2017-09-04 13:44:48.410822: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?,?], [?,?], [?], [?]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
2017-09-04 13:44:48.410832: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?,?], [?,?], [?], [?]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
  eval dev: perplexity 12.68, time 0s, Mon Sep  4 13:44:48 2017.
  eval test: perplexity 1.00, time 0s, Mon Sep  4 13:44:48 2017.
2017-09-04 13:44:48.450953: W tensorflow/core/kernels/lookup_table_init_op.cc:347] Table trying to initialize from file vmr_data/vocab.sn is already initialized.
2017-09-04 13:44:48.450984: W tensorflow/core/kernels/lookup_table_init_op.cc:347] Table trying to initialize from file vmr_data/vocab.sn is already initialized.
2017-09-04 13:44:48.451636: W tensorflow/core/kernels/lookup_table_init_op.cc:347] Table trying to initialize from file vmr_data/vocab.en is already initialized.
  loaded infer model parameters from vmr_model/translate.ckpt-1000, time 0.03s
# External evaluation, global step 1000
  decoding to output vmr_model/output_dev.
2017-09-04 13:44:48.647793: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
2017-09-04 13:44:48.647813: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
  done, num sentences 51, time 0s, Mon Sep  4 13:44:48 2017.
('Ref: ', 4018)
  bleu dev: 1.8
  saving hparams to vmr_model/hparams
# External evaluation, global step 1000
  decoding to output vmr_model/output_test.
2017-09-04 13:44:48.684772: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
2017-09-04 13:44:48.684857: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
  done, num sentences 0, time 0s, Mon Sep  4 13:44:48 2017.
('Ref: ', 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pksingh/nmt/nmt/nmt.py", line 495, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/pksingh/nmt/nmt/nmt.py", line 488, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/pksingh/nmt/nmt/nmt.py", line 481, in run_main
    train_fn(hparams, target_session=target_session)
  File "nmt/train.py", line 215, in train
    sample_tgt_data)
  File "nmt/train.py", line 141, in run_full_eval
    infer_model, infer_sess, model_dir, hparams, summary_writer)
  File "nmt/train.py", line 129, in run_external_eval
    save_on_best=False)
  File "nmt/train.py", line 446, in _external_eval
    decode=decode)
  File "nmt/utils/nmt_utils.py", line 80, in decode_and_evaluate
    bpe_delimiter=bpe_delimiter)
  File "nmt/utils/evaluation_utils.py", line 36, in evaluate
    bpe_delimiter=bpe_delimiter)
  File "nmt/utils/evaluation_utils.py", line 89, in _bleu
    per_segment_references, translations, max_order, smooth)
  File "nmt/scripts/bleu.py", line 105, in compute_bleu
    ratio = float(translation_length) / reference_length
ZeroDivisionError: float division by zero
`

**Comment by aaryavrate** [comment]
Ah, after 4 hours of breaking my head, as soon as I posted, it flashed that test.en file is empty. LOL
