### ISSUE TITLE
Error：“AttributeError: 'MapDataset' object has no attribute 'apply' “ in recent commit

### ISSUE THREAD

**Issue by alucardpj** [tensorflow/nmt#99]
environment:

> os: windows 10
> python: 3.6.2
> tensorflow ver: 1.3.0 gpu
> nmt commit: bc62c01beb4c2cb4b3c0665e138ba1c6203cff0f

when running nmt with command：

> python -m nmt.nmt --src=vi --tgt=en --vocab_prefix=e:\vdata\nmt\nmt_data\vocab --train_prefix=e:\vdata\nmt_new\nmt_data\train --dev_prefix=e:\vdata\nmt_new\nmt_data\tst2012 --test_prefix=e:\vdata\nmt_new\nmt_data\tst2013 --out_dir=e:\vdata\nmt_new\nmt_model --num_train_steps=12000 --steps_per_stats=100 --num_layers=2 --num_units=128 --dropout=0.2 --metrics=bleu

Error trace:

> Traceback (most recent call last):
  File "C:\Users\pengjian\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pengjian\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\vdata\nmt_new\nmt\nmt.py", line 511, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\pengjian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:\vdata\nmt_new\nmt\nmt.py", line 504, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "E:\vdata\nmt_new\nmt\nmt.py", line 497, in run_main
    train_fn(hparams, target_session=target_session)
  File "E:\vdata\nmt_new\nmt\train.py", line 171, in train
    train_model = model_helper.create_train_model(model_creator, hparams, scope)
  File "E:\vdata\nmt_new\nmt\model_helper.py", line 86, in create_train_model
    skip_count=skip_count_placeholder)
  File "E:\vdata\nmt_new\nmt\utils\iterator_utils.py", line 194, in get_iterator
    batched_dataset = src_tgt_dataset.apply(
AttributeError: 'MapDataset' object has no attribute 'apply'

but if I reset the master branch to commit 04c8c04a8b4e805f3d0a9c42b4d17c85f1324c55, it will be fine to run the process without error.

so what make error with the recent commits?

**Comment by oahziur** [comment]
@alucardpj The master branch requires TensorFlow Nightly. You can use the [tf-1.2 branch](https://github.com/tensorflow/nmt/tree/tf-1.2) for tensorflow 1.3.0

**Comment by alucardpj** [comment]
thanks a lot, I'll try the nightly ver of TensorFlow.

**Comment by harishdamera** [comment]
I have similar error. I installed Tensorflow Nightly, but still have the same error.
